use_frameworks!

'echo "2.3" > .swift-version'

target 'FinalObjectiveC_Example' do
  pod 'FinalObjectiveC', :path => '../'

  target 'FinalObjectiveC_Tests' do
    pod 'FinalObjectiveC', :path => '../'
  end
end
